### ISSUE TITLE
百度编辑器的使用

### ISSUE THREAD

**Issue by jia253** [mojifan/yii1-another-ueditor-extension#1]
我的提示  请求地址错误，上传文件用不了、怎么解决啊

**Comment by jia253** [comment]
Uncaught TypeError: Cannot read property 'style' of null‍
抱这个错了




------------------ 原始邮件 ------------------
发件人: "墨迹凡";<notifications@github.com>;
发送时间: 2015年4月2日(星期四) 下午5:16
收件人: "mojifan/yii1-another-ueditor-extension"<yii1-another-ueditor-extension@noreply.github.com>; 
抄送: "~劣&徒~"<jia253@qq.com>; 
主题: Re: [yii1-another-ueditor-extension] 百度编辑器的使用 (#1)




用浏览器的开发者工具 看一下请求的上传地址是什么？

**Comment by mojifan** [comment]
可否贴一下代码，或者截图 ，编辑器正常显示出来了？除了上传功能，其他功能都能正常使用？
